mysql: 
  username: "root"     #账号
  password: "123456"   #密码
  host: "39.101.73.74" #数据库地址，可以是Ip或者域名
  port: 3306           #数据库端口
  dbName: "douyin"     #数据库名
  #timeout: "10s"       #连接超时，10秒
  #maxOpenConns: 100    #设置数据库连接池最大连接数
  #maxIdleConns: 20     #连接池最大允许的空闲连接数，如果没有sql任务需要执行的连接数大于20，超过的连接会被连接池关闭。

server:
  name: douyin
  host: 0.0.0.0
  port: 8080